default_language_version:
  python: python3
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/python-poetry/poetry
  rev: '1.2.2'
  hooks:
    - id: poetry-check
    # Since poetry-lock is disabled on the CI, run this so that we still fail if needed on the CI
    - id: poetry-check
      name: poetry-lock-check
      entry: poetry lock --check
      files: ^pyproject\.toml|poetry\.lock$
    - id: poetry-lock
      files: ^pyproject\.toml|poetry\.lock$
      args: ["--no-update"]
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
    - id: poetry-export
      args: ["--with", "dev", "-f", "requirements.txt", "-o", "dev-requirements.txt", "--without-hashes"]
    - id: poetry-export
      args: ["--with", "dev,plugin-test", "-f", "requirements.txt", "-o", "dev-requirements-extras.txt", "--without-hashes"]
ci:
  autofix_prs: true
  autoupdate_branch: develop
  autoupdate_schedule: weekly
  skip: [poetry-lock]  # No network access from the pre-commit CI