[project]
name = "Flexget"
description = """\
    FlexGet is a program aimed to automate downloading or processing content (torrents, podcasts, etc.) from \
    different sources like RSS-feeds, html-pages, various sites and more.\
"""
authors = [
    { name = "Marko Koivusalo", email = "marko.koivusalo@gmail.com" },
    { name = "Chase Sterling", email = "chase.sterling@gmail.com" },
]
dependencies = [
    "apscheduler>=3.2.0",
    "beautifulsoup4>=4.5",
    "colorama>=0.4.4",
    "feedparser>=6.0.2",
    "guessit~=3.4",
    "html5lib>=0.11",
    "jinja2~=3.0",
    "jsonschema<4.0,>=2.0",
    "loguru>=0.4.1",
    "more-itertools",
    "psutil>=5.8.0",
    "pynzb",
    "pyrss2gen",
    "python-dateutil",
    "pyyaml>=4.2b1",
    "rebulk>=2.0.0",
    "requests>=2.20.0",
    "rich>=9.0.0",
    "rpyc~=5.0",
    "sqlalchemy<1.999,>=1.3.10",
    "cherrypy>=18.0.0",
    "flask-compress>=1.2.1",
    "flask-cors>=2.1.2",
    "flask-login>=0.4.0",
    "flask-restful>=0.3.3",
    "flask-restx>=0.5.1",
    "flask>=0.7",
    "packaging~=21.3",
    "pyparsing==2.4.7",
    "werkzeug<2.1.0",  # flask-restx 0.5.1 is holding this back
    "zxcvbn-python"
]
requires-python = ">=3.7"
readme = "README.rst"
license = { file = "LICENSE" }
dynamic = ["version"]

[project.optional-dependencies]

[project.scripts]
flexget = "flexget:main"

[project.gui-scripts]
flexget-headless = "flexget:main"  # This is useful on Windows to avoid a cmd popup

[tool.pdm]
version = { source = "file", path = "flexget/_version.py" }
[tool.pdm.dev-dependencies]
dev = [
    "black>=18.9b0",
    "pytest>=7.1.3",
    "codacy-coverage>=1.2.18",
    "coverage~=6.0",
    "isort>=5.5.1",
    "pre-commit>=2.9.0",
    "pylint>=2.6.0",
    "pytest-cov>=3.0.0",
    "pytest-runner>=6.0.0",
    "pytest-xdist>=2.4.0",
    "sphinx~=4.3.0",
    "sqlalchemy-stubs>=0.4",
    "vcrpy>=4.1.1",
]
plugin-tests = [
    "boto3>=1.24.91",
    "subliminal>=2.0rc1",
]
release = [
    # For dev_tools.py
    "click>=8.0.0",
    "requests",
    # For update-changelog.py
    "gitpython~=3.1.18",
]

[tool.pdm.build]
excludes = [
    "flexget/tests/*"
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
testpaths = ["flexget/tests"]

[tool.black]
line-length = 99
skip-string-normalization = true
target-version = ['py37', 'py38', 'py39', 'py310']
# Only include files in /flexget/, or directly in project root
include = '^/(flexget/.*)?[^/]*\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.idea
    | dist
    | flexget/ui
  )/
)
'''

[tool.isort]
profile = 'black'
line_length = 99
known_first_party = ['flexget']
