[tool.poetry]
name = "flexget"
version = "0.0.0"  # This is not managed here at the moment, since we are still building with setuptools
description = """FlexGet is a program aimed to automate downloading or processing content (torrents, podcasts, etc.) \
from different sources like RSS-feeds, html-pages, various sites and more."""
authors = [
    "Marko Koivusalo <marko.koivusalo@gmail.com>",
    "Chase Sterling <chase.sterling@gmail.com"
]
license = "MIT"
readme = "README.rst"
exclude = [
    "flexget/tests"
]

[tool.poetry.dependencies]
python = "^3.7"
apscheduler = ">=3.2.0"
beautifulsoup4 = ">=4.5"
click = "^8.1.3"
colorama = ">=0.4.4"
feedparser = ">=6.0.2"
guessit = ">=3.4,<4.0"
html5lib = ">=0.11"
jinja2 = ">=3.0,<4.0"
jsonschema = ">=2.0"
loguru = ">=0.4.1"
more-itertools = "^8.14.0"
psutil = ">=5.8.0"
pynzb = "^0.1.0"
pyrss2gen = "^1.1"
python-dateutil = "^2.8.2"
pyyaml = ">=4.2b1"
rebulk = ">=2.0.0"
requests = ">=2.20.0"
rich = ">=9.0.0"
rpyc = ">=5.0,<6.0"
sqlalchemy = ">=1.3.10,<1.999"
cherrypy = ">=18.0.0"
flask-compress = ">=1.2.1"
flask-cors = ">=2.1.2"
flask-login = ">=0.4.0"
flask-restful = ">=0.3.3"
flask-restx = "0.5.1"
flask = ">=0.7"
packaging = ">=21.3,<22.0"
pyparsing = ">=2.4.7"
werkzeug = "<2.1.0"
zxcvbn-python = "^4.4.24"


[tool.poetry.group.dev.dependencies]
black = ">=18.9b0"
boto3 = "^1.24.89"
codacy-coverage = ">=1.2.18"
coverage = ">=6.0,<=6.2"
gitpython = ">=3.1.18,<3.1.24"
isort = ">=5.5.1"
pre-commit = ">=2.9.0"
pylint = ">=2.6.0"
pytest-cov = ">=3.0.0,<3.1.0"
pytest-runner = "^6.0.0"
pytest-xdist = ">=2.4.0,<2.5.0"
pytest = ">=6.2.4,<6.3.0"
sphinx = ">=4.3.0,<4.4.0"
sqlalchemy-stubs = "^0.4"
twine = ">=3.6.0,<3.7.0"
vcrpy = ">=4.1.1,<4.2.0"
wheel = ">=0.37.0,<0.38.0"

[tool.poetry.group.plugin-test.dependencies]
# These are optional dependencies for plugins that have tests in the test suite
subliminal = ">= 2.0rc1"
importlib-metadata = "<5.0.0"  # subliminal breaks on python 3.7 right now without this upper bound

[tool.poetry.scripts]
flexget = 'flexget:main'

[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 99
skip-string-normalization = true
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
# Only include files in /flexget/, or directly in project root
include = '^/(flexget/.*)?[^/]*\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.idea
    | dist
    | flexget/ui
  )/
)
'''

[tool.isort]
profile = 'black'
line_length = 99
known_first_party = ['flexget']
