name: Changelog Update

on:
  push:
    branches:
    - develop

permissions:
  contents: read

jobs:
  update-changelog:
    permissions:
      contents: write  # for Git to git push
    name: Update Changelog
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.7
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/checkout@v3
      with:
        repository: Flexget/wiki
        path: wiki
        token: ${{ secrets.flexgetbot_pat }}
        ref: main
    - name: Setup Git User
      run: |
        git config --global user.email ${{ secrets.git_email }}
        git config --global user.name ${{ secrets.git_user }}
    - uses: pdm-project/setup-pdm@main
      name: Setup PDM
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        version: 2.1.5
    - name: Install dev dependencies
      run: |
        pdm install --dev -G release --no-default --no-self
    - name: Update the Changelog
      run: |
        set -x
        pdm run python update-changelog.py wiki/ChangeLog.md
        cd wiki
        git add ChangeLog.md
        if ! git diff --cached --exit-code; then
            git commit -m "Automated ChangeLog update"
            git push origin main
        fi
