name: Trigger Deploy

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  deploy:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to create deployment

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/github-script@v7
        name: Create Deployment
        with:
          github-token: ${{ secrets.flexgetbot_pat }}
          script: |
            await github.rest.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
            });
