name: Trigger Deploy

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  deploy:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to create deployment

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@0.9.0
        name: Create Deployment
        with:
          github-token: ${{ secrets.flexgetbot_pat }}
          script: |
            await github.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
            });
